### ISSUE TITLE
在 App.vue 中编写标签的全局样式无效，如 button 和 input 等

### ISSUE THREAD

**Issue by rhzone** [dcloudio/uni-app#1065]
**问题描述**
- 在 App.vue 中编写标签的全局样式无效，如 button 和 input 等

代码样例如下

```css
button {
   border-radius: 0;
   border: none;
   margin: 0;
}
````

**系统信息:**
 - 发行平台: 微信小程序
 - 设备信息: 微信开发者工具模拟器 和 Android 真机都无效
