### ISSUE TITLE
h5端非scoped css 不能正确编译

### ISSUE THREAD

**Issue by Starrah** [dcloudio/uni-app#1095]
**问题描述**
当在vue文件里定义普通的`<style>`而非`<style scoped>`（这样做是因为我确实希望对某些组件内部的css做出调整，希望达到组件穿透的效果）时，`<style>`内容不能被正确编译。
`<style scoped>`的编译原理是通过在页面的所有标签上加上data属性，然后所有scoped style会自动带上这个属性的选择器，那么反之普通的style就不应该选择data属性的。
上述在微信平台是正确的，然而在h5平台，即使是普通的`<style>`也会被编译出data属性。

**复现步骤**
下述测试用代码可在我的github中找到：[代码链接](https://github.com/Starrah/bugtest2)

1. 新建项目（我是用vue cli建的默认项目），建立子组件components/childtest.vue文件，代码如下：
```vue
<template>
    <view>
        <text>测试文字</text>
    </view>
</template>

<script>
    export default {
        name: "childtest"
    }
</script>

<style scoped>

</style>
```
2. pages/index/index.vue文件改为如下代码，其中引用childtest子组件：
```vue
<template>
	<view class="content">
		<childtest></childtest>
	</view>
</template>

<script>
	import Childtest from '../../components/childtest'
	export default {
		components: {Childtest},
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {

		},
		methods: {

		}
	}
</script>

<style>
	childtest text{
		color: green;
	}
</style>

```
3. 分别npm run dev:mp-weixin和npm run dev:h5。

**预期结果**
npm run dev:mp-weixin，微信产生的就是正常的预期结果。
看到非scoped的style的编译结果为如下，css选择器中没有带上data，css正常生效（子组件显示为绿色）；
![image](https://user-images.githubusercontent.com/46821571/70390229-13a51a00-1a04-11ea-831a-c81beb777f83.png)

**实际结果**
npm run dev:h5，h5产生的就是错误结果。
看到非scoped的style的编译结果为如下，css选择器中却带了data，于是导致css没有生效（子组件还是黑色）；
![image](https://user-images.githubusercontent.com/46821571/70390248-36cfc980-1a04-11ea-8688-7306ba85bf62.png)

**系统信息:**
 - 发行平台:H5平台
 - 操作系统:测试环境是Windows10, Chrome浏览器
 - uni-app版本：npm run info运行结果
uni-app v2.4.2
uni-app cli v2.0.0-24220191115006

Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 10.16.0 - D:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-h5: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-helper-json: * => 1.0.3
    @dcloudio/uni-mp-alipay: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-baidu: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-qq: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-toutiao: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-weixin: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-stat: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-template-compiler: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.1
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-plugin-router:  4.1.1
    @vue/cli-plugin-vuex:  4.1.1
    @vue/cli-service: ^4.1.0 => 4.1.1
    @vue/cli-shared-utils:  3.12.1
    @vue/component-compiler-utils:  3.0.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.2
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.2
  npmGlobalPackages:
    @vue/cli: Not Found

**补充信息**
[根据你的分析，出现这个问题的原因可能在哪里？]
我认为可能是h5端的css编译器有问题了？导致未能处理非scoped的css，全都按照scoped处理的？

**Comment by fxy060608** [comment]
h5 平台，除了App.vue里的，其他vue文件style均强制scoped

**Comment by Starrah** [comment]
哦哦 是这样吗 好的 非常感谢

那我也分享一下我的解决方案供之后遇到同一问题的人参考
就是使用>>>穿透选择器 但是这个在微信的css编译器会无法编译的，所以需要使用条件编译
代码类似如下：
```css
    /*  #ifdef H5  */
    switch.ansg >>> .uni-switch-input, switch.ansg >>> .wx-switch-input{
        width: 70px;
    }
    switch.ansg >>> .uni-switch-input-checked::after, switch.ansg >>> .wx-switch-input-checked::after {
        left: 44px;
    }
    /*  #endif  */
    /*  #ifndef H5  */
    switch.ansg .uni-switch-input, switch.ansg .wx-switch-input{
        width: 70px;
    }
    switch.ansg .uni-switch-input-checked::after, switch.ansg .wx-switch-input-checked::after {
        left: 44px;
    }
    /*  #endif  */
```
注：在非h5平台非scoped的style是正常编译的，所以不用写>>>就可以达到穿透效果
