### ISSUE TITLE
less 双斜线注释支持

### ISSUE THREAD

**Issue by F-loat** [dcloudio/uni-app#128]
less 的语法是支持双斜线注释的，但是目前使用会报错 `Unrecognised input. Possibly missing something`

``` less
div {
  border-bottom: 1px solid #fff;
  /* border-bottom: 1px solid #000; */
  // border-bottom: 1px solid #000;
}
```
