### ISSUE TITLE
关于修改vant样式的问题

### ISSUE THREAD

**Issue by zhoufanglu** [dcloudio/uni-app#1568]
我在某个路由里面引入了`vant`的组件
我现在需要修改`vant`组件的样式
无法在当前路由修改样式吗？写了`css`没有生效
在全局内就有效

组件内无效，全局css中就有效果，请问为什么
```css
<style lang="scss">
    .p-head-component{
        border: solid 1px black;
        .van-nav-bar{
             background-color: red!important;
         }
    }
</style>
```
