### ISSUE TITLE
textarea能不能在auto-height的时候允许配置一个初始高度

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1669]
开启了auto-height之后，能不能实现设置一个初始化的高度。

**Comment by zhetengbiji** [comment]
你说的是这种吗？
```css
textarea {
  min-height: 3em;
}
```
