### ISSUE TITLE
-upx单位错误 以及不同平台v-for指令的差异

### ISSUE THREAD

**Issue by uioz** [dcloudio/uni-app#180]
# 平台

- windows10
- HbuilderX 1.5.2.20190121
- Android 8.1.1(三星note8)

# 问题1 -upx计算错误

有如下template代码:
```html
	<view class="container">
		<view class="container-full">
			
		</view>
	</view>
```
如下CSS代码:
```css
	.container{
		margin: 0 34upx;
	}
	
	.container-full{
		margin: 30upx -34upx;
	}
```
![default](https://user-images.githubusercontent.com/36815772/51795463-f669c180-221e-11e9-851b-b3c83b8780f5.jpg)

这个问题花了我很长时间才找到,他导致了真机模拟,页面中出现了横向滚动条

H5没有问题但计算值是错误的,真机模拟android平台会出现横向滚动条.

# 问题2 v-for指令不同平台有差异

v-for指令可以按照数值大小进行遍历:
```html
<view v-for="item in number">{{item}}</view>
```
这里不同平台的起始值的输出不同:
- H5 以1开始,标准行为
- 真机模拟(Android) 以0开始

# 问题3 真机模拟到底支持不支持条件编译

如题,为了解决上面的问题我在真机模拟的时候使用条件编译但是编译报错.
