### ISSUE TITLE
关于uni-app文档中css使用本地背景图的错误

### ISSUE THREAD

**Issue by 643104191** [dcloudio/uni-app#2072]
**问题描述**
文档连接:[背景图片](https://uniapp.dcloud.io/frame?id=%E8%83%8C%E6%99%AF%E5%9B%BE%E7%89%87)
文档描述中需要使用如下方法来使用本地背景图
```css
 .test2 {
     background-image: url('~@/static/logo.png');
 }
```
最终在app端编译出的路径是`/static/logo.png`
app端webview的href是`file:///storage/emulated/0/Android/data/com.xxx.app/apps/__UNI__xxxx/www/__uniappview.html`
最终请求的图片地址就是`file://static/logo.png`
实际上应该请求`file:///storage/emulated/0/Android/data/com.xxx.app/apps/__UNI__xxxx/www/static/logo.png`
所以编译出来的路径应该是`./static/logo.png`而不是`/static/logo.png`

**复现步骤**
1. 使用vue-cli创建uni-app项目
2. 在css代码中写上述"问题描述"中的css代码
3. 执行真机调试

**预期结果**
预期应该编译出
```css
 .test2 {
     background-image: url('./static/logo.png');
 }
```

**实际结果**
而实际编译出
```css
 .test2 {
     background-image: url('/static/logo.png');
 }
```

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统: Android 7.0
 - HBuilderX版本: 2.8.8.20200820
 - uni-app版本: v2.8.8
 - uni-app cli版本: v2.0.0-28820200820001
