### ISSUE TITLE
css文件中front-face压缩成一行后编译报错

### ISSUE THREAD

**Issue by lmf** [dcloudio/uni-app#2206]
**问题描述**
引入第三方库的css文件是压缩过的，通过分析是@font-face的内容在压缩成一行后会报错，格式化后就没问题

**复现步骤**
新建个css文件，内容如下，然后在main.js中import它，编译就会报错
```css
@font-face{font-weight:400;font-family:vant-icon;font-style:normal;font-display:auto;src:url(https://img.yzcdn.cn/vant/vant-icon-96970a.woff2) format('woff2'),url(https://img.yzcdn.cn/vant/vant-icon-96970a.woff) format('woff'),url(https://img.yzcdn.cn/vant/vant-icon-96970a.ttf) format('truetype')}
```

uni-app使用的cli是最新版本2.0.0-29320201014001
