### ISSUE TITLE
伪元素编译为小程序异常

### ISSUE THREAD

**Issue by quanzaiyu** [dcloudio/uni-app#2536]
**问题描述**

伪元素编译为小程序异常，编译结果为 `--`。其他端仅测试了H5端编译结果正常。

**复现步骤**

1. 在样式中添加伪元素
2. 编译为小程序
3. 编译结果无效

示例代码：

```vue
<template lang='pug'>
.wrapper
  ...
  .test 123
  ...
</template>

<script>
...
export default {
...
}
</script>

<style lang="stylus" scoped>
.test
  position relative
  &::after
    content ''
    position absolute
    top 50rpx
    left 0
    width 100rpx
    height 100rpx
    background-color #f00
</style>
```

编译结果：

```css
.test.data-v-57280228 {
  position: relative;
}
.tes--.data-v-57280228:after {
  content: '';
  position: absolute;
  top: 50rpx;
  left: 0;
  width: 100rpx;
  height: 100rpx;
  background-color: #f00;
}
```

相关截图：

源代码：
![Snipaste_2021-03-15_14-00-15](https://user-images.githubusercontent.com/13745132/111111695-c8c86980-8599-11eb-9068-ef7f4b1030e6.png)

微信小程序端编译结果（异常）：

![Snipaste_2021-03-15_14-01-02](https://user-images.githubusercontent.com/13745132/111111705-cbc35a00-8599-11eb-9bc0-a717fae93e16.png)

H5端编译结果（正常）：

![Snipaste_2021-03-15_14-01-45](https://user-images.githubusercontent.com/13745132/111111714-cebe4a80-8599-11eb-9e24-54dbf1cd07bd.png)

**预期结果**

预期编译结果为：

```css
.test.data-v-57280228 {
  position: relative;
}
.test.data-v-57280228:after {
  content: '';
  position: absolute;
  top: 50rpx;
  left: 0;
  width: 100rpx;
  height: 100rpx;
  background-color: #f00;
}
```

**实际结果**

实际编译结果：

```css
.test.data-v-57280228 {
  position: relative;
}
.tes--.data-v-57280228:after {
  content: '';
  position: absolute;
  top: 50rpx;
  left: 0;
  width: 100rpx;
  height: 100rpx;
  background-color: #f00;
}
```

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: Windows10
 - uni-app版本: 2.0.0-31420210305001
 - 设备信息: 任何移动端设备

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

经过测试，无论是否使用预编译语言（less、sass、stylus），都会导致编译结果异常。初步判断是uniapp小程序编译器的问题。
