### ISSUE TITLE
打包小程序，样式编译条件失效

### ISSUE THREAD

**Issue by robinv8** [dcloudio/uni-app#3149]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
打包小程序，样式编译条件失效
**复现步骤**
[复现问题的步骤]
```css
/*  #ifdef  MP-WEIXIN  */
.bg {
  background-image: url(https://cdn.baidu.com/bg.jpg);
}
/* #endif */

/*  #ifdef  H5  */
.bg {
  background-image: url('@/assets/bg.png');
}
/* #endif */
```
**预期结果**

只保留小程序下对应的背景图
**实际结果**
打包 h5正常，小程序异常
![image](https://user-images.githubusercontent.com/12277531/148082393-bfcf8d51-a04e-4f9d-b290-eeff06559656.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - uni-app版本  v3.1.22
 - 设备信息  微信开发者工具

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
