### ISSUE TITLE
vue3 微信小程序的css 深度选择器失效

### ISSUE THREAD

**Issue by Michael-py001** [dcloudio/uni-app#3688]
**问题描述**
vue3 微信小程序的css 深度选择器失效，在h5里正常

**复现步骤**
```html
<view class="equal-division">
        <u-image src="xxx" v-for="(item,index) in 4" :key="index"></u-image>
</view>
```
```css
.equal-division {
     margin-top: 22rpx;
    ::v-deep .u-image {
      margin-right: 27rpx;
    }
   }
```
![image](https://user-images.githubusercontent.com/60598432/177905870-517b7a0f-87a4-42d5-87ce-aa0f3437ed9e.png)
在h5里css加上去了
![image](https://user-images.githubusercontent.com/60598432/177906223-c0bca3e6-eb7f-49e8-a32d-b8b7fd774543.png)
但是微信小程序里失效

但是同样的语法，在微信小程序里其他的两个页面可以正常渲染，但是到了这个页面我使用的时候就怎么写都不生效，编译到h5就正常

**系统信息:**
 - HBuilderX版本3.5.1.20220707-alpha
