### ISSUE TITLE
小程序 scss文件 在样式嵌套的情况下条件编译不生效

### ISSUE THREAD

**Issue by amihhs** [dcloudio/uni-app#3697]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
小程序 scss文件 在样式嵌套的情况下条件编译不生效

**复现步骤**
[复现问题的步骤]

```scss
.reset {
  color: red;

  /* #ifndef MP-WEIXIN*/
  .AAA+* {
    color: red;
  }
  /* #endif */
}
```

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
```scss
.reset {
  color: red;
}
```
**实际结果**
[这里请贴上你的报错截图或文字]
```scss
.reset {
  color: red;
}
.reset .AAA + * {
  color: red;
}
```

**系统信息:**
 - 发行平台: [微信小程序、字节小程序、百度小程序]
 -cli 3.0.0-alpha-3050120220706002

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
