### ISSUE TITLE
v-bind 在css中使用不生效

### ISSUE THREAD

**Issue by gyhyfj** [dcloudio/uni-app#3982]
release: v3.0.0-alpha-3060420220922001

编译成小程序，但确实看到编译成了css3变量

复现过程如下

```css
// script 中
const picwidth = ref('100px')

// style 中
.pic{
  width: v-bind(picwidth)
}
```
