### ISSUE TITLE
safari地址栏设置在底部，底部内容区判断不准备，遮盖导航栏

### ISSUE THREAD

**Issue by milo-wjh** [dcloudio/uni-app#4083]
**问题描述**
IOS15以后 safari浏览器可以设置地址栏在底部，设置后浏览器内容区域判断没有去掉地址栏高度，导致内容被地址栏遮盖
![image](https://user-images.githubusercontent.com/20457324/209260375-5730a8bb-8050-45c2-b38f-1a79f46ba6ea.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统  iOS 16.2 
 - uni-app版本 
    uni-app v3.6.4
    uni-app cli v2.0.1-36420220922003
 - 设备信息  iPhone8 Plus

**Comment by StrivingRabbit** [comment]
底部是你自定义的？

**Comment by StrivingRabbit** [comment]
```css
bottom {
bottom: 0;
    padding-bottom: 0;
    padding-bottom: constant(safe-area-inset-bottom);
    padding-bottom: env(safe-area-inset-bottom);
}
```

用这样的css处理一下试试
