### ISSUE TITLE
uni-app H5 原生组件的 dark mode 适配

### ISSUE THREAD

**Issue by ousing9** [dcloudio/uni-app#4317]
**新功能描述**

根据`manifest.json`中是否开启`darkmode`来决定 H5 中使用原生组件时是否使用深色主题。

**现状及问题**

目前 H5 使用原生组件时，dark mode 是直接使用`@media`来实现的，这并**不适用于页面未做暗黑主题适配的情况**，当用户的浏览器偏好是深色时，**只有这几个组件变深色**，导致样式很奇怪。

以 switch 组件为例，`src/core/view/components/switch/index.vue`，目前 dark mode 的适配 CSS 代码为：

```css
@media (prefers-color-scheme: dark) {
    uni-switch .uni-switch-input {
        border-color: #3b3b3f;
    }

    uni-switch .uni-switch-input,
    uni-switch .uni-switch-input:before {
        background-color: #3b3b3f;
    }

    uni-switch .uni-switch-input:after {
        background-color: #fff;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.4);
    }

    uni-switch .uni-checkbox-input {
        background-color: #2c2c2c;
        border: 1px solid #656565;
    }
}
```

我的系统主题偏好是深色，但是我的页面并没有做深色主题适配，结果在我打包的页面中出现了这样的样式（开发环境下是没有的）。尝试了加`<meta name="color-scheme" content="light">`、加`html { color-scheme: light; }`等方法全都没办法将 switch 组件恢复亮色主题样式。目前的解决方法是在打包出来的 CSS 中处理掉`@media`代码。

<img src="https://user-images.githubusercontent.com/32257773/236628431-8e66243c-5ae5-4e9a-ac29-867f5433c774.png" />

**尝试方案**

个人认为可以参考 Stack Overflow 的这个问题中的高赞答案：[How to override css prefers-color-scheme setting](https://stackoverflow.com/questions/56300132/how-to-override-css-prefers-color-scheme-setting)，同时参考浏览器 [Dark Reader](https://github.com/darkreader/darkreader) 插件的工作原理（这两种方法挺像的），结合`manifest.json`的`darkmode`配置来处理深色主题组件的样式。

我对 uni-app 的源代码并不熟悉，不知道怎么改相关的内容，抱歉没办法提 PR。

感觉目前在 H5 开发中做了深色主题适配的人应该还是比较少的，这确实对 H5 开发造成影响了，是否可以考虑暂时将这些 H5 用的原生组件的深色主题适配代码去掉？实际需要做深色主题适配的人自行加上这些代码就可以了。（反正都写了一大堆深色主题适配代码了，不差这一点吧）
