### ISSUE TITLE
.uni-tabbar-bottom 选择器隐藏tabbar 在APP上无效

### ISSUE THREAD

**Issue by dong-lufei** [dcloudio/uni-app#4412]
比如我 pages.json 文件里有2个页面的tabbar
```json
"tabBar": {
    "list": [
	    {
		    "pagePath": "pages/index/index",
		    "text": "1"
    },
	    {
		    "pagePath": "pages/page2/page2",
		    "text": "2"
    }
]
```
在 APP.vue 或 pages下面的页面文件比如 index.vue 里的 css 里写样式(加深度样式也是)都【没有隐藏APP端】的 tabbar 栏
```css
.uni-tabbar-bottom {
  display: none;
}
```
