### ISSUE TITLE
小程序build之后，首页wxss文件中出现一些无关样式

### ISSUE THREAD

**Issue by DPFlying** [dcloudio/uni-app#460]
**问题描述**
小程序build之后，首页wxss文件中出现一些无关样式，dev时不存在这个问题，其他页面也没有这个问题，只有首页存在这个问题

**复现步骤**
首页代码，不包含任何样式代码
```html
<template>
  <view>首页</view>
</template>
```
build之后，首页的wxss文件中出现如下样式代码
```css
page::after {
  position: fixed;
  content: '';
  left: -1000px;
  top: -1000px;
  -webkit-animation: shadow-preload 0.1s;
  -webkit-animation-delay: 3s;
  animation: shadow-preload 0.1s;
  animation-delay: 3s;
}
@-webkit-keyframes shadow-preload {
  0% {
    background-image: url(https://cdn.dcloud.net.cn/img/shadow-grey.png);
  }
  100% {
    background-image: url(https://cdn.dcloud.net.cn/img/shadow-grey.png);
  }
}
@keyframes shadow-preload {
  0% {
    background-image: url(https://cdn.dcloud.net.cn/img/shadow-grey.png);
  }
  100% {
    background-image: url(https://cdn.dcloud.net.cn/img/shadow-grey.png);
  }
}
```

**预期结果**
build之后首页的wxss文件不存在任何样式代码

**实际结果**
build之后首页的wxss文件中出现无关样式代码

**系统信息:**
```
Environment Info:
  System:
    OS: Windows 10
  Binaries:
    Node: 10.16.0
    Yarn: 1.16.0
    npm: 6.9.0
  npmPackages:
    @dcloudio/types: * => 0.1.8
    @dcloudio/uni-app-plus: * => 0.0.243
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.962
    @dcloudio/uni-h5: * => 0.5.10
    @dcloudio/uni-mp-alipay: * => 0.0.817
    @dcloudio/uni-mp-baidu: * => 0.0.844
    @dcloudio/uni-mp-qq: * => 0.0.101
    @dcloudio/uni-mp-toutiao: * => 0.0.341
    @dcloudio/uni-mp-weixin: * => 0.0.962
    @dcloudio/uni-template-compiler: * => 0.9.179
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 0.9.524
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.479
    @dcloudio/webpack-nvue-entry-loader:  0.0.1
    @dcloudio/webpack-uni-mp-loader: * => 0.3.630
    @dcloudio/webpack-uni-pages-loader: * => 0.2.845
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-plugin-typescript: ^3.5.1 => 3.8.1
    @vue/cli-service: ^3.8.0 => 3.8.3
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^6.3.2 => 6.3.2 (7.1.0)
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-property-decorator: ^8.0.0 => 8.1.1
    vue-router:  3.0.1
    vue-style-loader:  3.1.2 (3.1.2)
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
    weex-vue-loader: ^0.7.0 => 0.7.0
```
