### ISSUE TITLE
build时候会删掉css中的兼容属性

### ISSUE THREAD

**Issue by lmf** [dcloudio/uni-app#712]
**问题描述**
像下面这种禁掉autoprefixer处理的注释，在dev下编译后会保留background: -webkit-linear-gradien，但更新uni-app后build时候会被删掉，猜测是build压缩css时候会删掉该注释，导致之后autoprefix删掉兼容的属性
`
/* autoprefixer: off */
 background: -webkit-linear-gradient(top, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 1));
`

**预期结果**
不删掉手动加的兼容属性

**系统信息:**
 - "vue-cli-plugin-uni": "^0.9.525
- "uni-mp-weixin": "^0.0.966"

**Comment by fxy060608** [comment]
根目录 postcss.config.js
```javascript
module.exports = {
  parser: require('postcss-comment'),
  plugins: [
    require('postcss-import'),
    require('autoprefixer')({
      remove: process.env.UNI_PLATFORM !== 'h5' // 可以先修改为 false，禁用 remove 试试
    }),
    require('@dcloudio/vue-cli-plugin-uni/packages/postcss')
  ]
}
```

**Comment by lmf** [comment]
@fxy060608 是发布到微信，remove: false后没问题。但框架build这块处理css时候应该是有问题的，应该处理下删除css注释的逻辑

**Comment by fxy060608** [comment]
> @fxy060608 是发布到微信，remove: false后没问题。但框架build这块处理css时候应该是有问题的，应该处理下删除css注释的逻辑

你原始的 postcss.config.js 是我贴的那样的代码吗？我测试你贴出来的代码，发行模式是不会被移除的
```css
 .test {
        background: -webkit-linear-gradient(top, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 1));
    }
```

**Comment by lmf** [comment]
@fxy060608 这样的：
```css
.test {
    background: -webkit-linear-gradient(top, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 1));
    background: linear-gradient(top, rgba(255, 255, 255, 0), rgba(255, 255, 255, 1));
}
```

**Comment by fxy060608** [comment]
> ```css
> .test {
>     background: -webkit-linear-gradient(top, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 1));
>     background: linear-gradient(top, rgba(255, 255, 255, 0), rgba(255, 255, 255, 1));
> }
> ```

测试结果：
源码
```css
.test {
    background: -webkit-linear-gradient(top, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 1));
    background: linear-gradient(top, rgba(255, 255, 255, 0), rgba(255, 255, 255, 1));
}
```
发行后：
```css
.test {
    background: -webkit-gradient(linear, left top, left bottom, from(rgba(255, 255, 255, 0)), to(rgba(255, 255, 255, 1)));
    background: -o-linear-gradient(top, rgba(255, 255, 255, 0), rgba(255, 255, 255, 1));
    background: linear-gradient(top, rgba(255, 255, 255, 0), rgba(255, 255, 255, 1));
}
```
