### ISSUE TITLE
【报Bug】页面滚动回到顶部控制台报错(app端)

### ISSUE THREAD

**Issue by 401819111** [dcloudio/uni-app#884]
## 详细问题描述
只有app端有问题,小程序没问题,h5未测试;
因为之前也提过一个滚动的bug,那个问题官方已经成功修复了,在更新hx版本后出现了现在这个问题.
[这是上一个滚动的bug](https://ask.dcloud.net.cn/question/78974)
有一个比较长的列表longList,有一个固定定位的元素item(点击后回到顶部)
出现的问题:
1. 点击item后页面会正常滚动到顶部,但是此时控制台一直在输出错误
2. 在上一个hx版本时(2.2.2.20190816)没有这个问题

在onPageScroll中输出scrollTop还可发现,报错的同时也会输出scrollTop,但是输出的值忽大忽小(报错内容见附件)

## 代码
[可重现代码片段]
```html
<view class="content">
		<view class="bgBox" />
		<view class="topBtn" @tap="goTop" />
</view>
```
```javascript
export default {
	data() {
		return {
			windowHeight: uni.getSystemInfoSync().windowHeight,
			topShow: false,
		}
	},
	onPageScroll(e) {
		console.log(e)
		let view = uni.createSelectorQuery().selectViewport();
		view.scrollOffset().exec();
	},
	methods: {
		goTop() {
			uni.pageScrollTo({
				scrollTop: 0,
				duration: 100
			});
		},
	}
}
```
```css
.bgBox {
		height: 8000px;
		background: linear-gradient(#fb5 35%, #58a 35%);
		background-size: 100% 30px;
	}
	.topBtn {
		background-color: #FF0000;
		position: fixed;
		bottom: 10%;
		right: 10%;
		width: 100px;
		height: 100px;
		border-radius: 50%;
	}
```

## IDE运行环境说明
HBuilderX:2.3.3.20190923
windows10 1903

## uni-app运行环境说明
app端运行,小程序没有问题,h5未测试
HBuilderX创建的
编译模式是自定义组件模式

## App运行环境说明

[Android版本号]
android 9

[手机型号]
一加7pro,三星s6

## 联系方式

[gmail]
lx401819111@gmail.com
                                                
附件可以看我在社区提的bug:[链接](https://ask.dcloud.net.cn/question/80483)
